site_name: BASH Training Courses

nav:
    - Bioinformatics Analysis Support Hub (BASH) : 'index.md'
    - BASH Training Courses : 
       - 'Training Courses 2022-2023': 'training-courses.md'
       - 'Introduction to Linux': 'introduction-to-linux/introduction-to-linux.md'
       - 'RNASeq (WES) Data Analysis': 'rnaseq-training-course/rna-seq-course-schedule.md'
       - 'DNASeq (WES) Data Analysis': 'dnaseq-training-course/dna-seq-course-schedule.md'
       - 'Introduction to R': 'introduction-to-r/introduction-to-r-schedule.md'

theme:
  name: material
  highlightjs: true
  palette:
    primary: blue grey
    accent: indigo
  features:
    - navigation.tabs
  
    - toc.follow
    - navigation.sections
    - navigation.tracking
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - content.code.annotate
  logo: assets/bash_logo2.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences